<?php

declare(strict_types=1);

namespace App\Modules\Pilgrimage\Database\Seeders;

use App\Modules\Pilgrimage\Models\PilgrimageRoute;
use App\Modules\Pilgrimage\Models\Stage;
use App\Modules\Pilgrimage\Models\Waypoint;
use Illuminate\Database\Seeder;

/**
 * 40 étapes principales France FR-01 → FR-40 (étapes de marche réelles, jours de repos exclus).
 *
 * Via Campaniensis : FR-01 → FR-15 (Rocroi → Vézelay, 23 étapes de marche mais
 *   numérotées 01-15 pour coller aux 40 GPX FR-*.gpx disponibles)
 * Voie de Vézelay GR654 : FR-16 → FR-40 (Vézelay → SJPP)
 *
 * Mapping GPX → étape :
 *   FR-01 → Signy (Rocroi→Sormonne→Signy), FR-02 → Château-Porcien, FR-03 → Reims,
 *   FR-04 → Verzy, FR-05 → Châlons, FR-06 → Vitry, FR-07 → Giffaumont,
 *   FR-08 → Montier, FR-09 → Bar-sur-Seine, FR-10 → Les Riceys,
 *   FR-11 → Tonnerre, FR-12 → Chablis, FR-13 → Auxerre, FR-14 → Arcy,
 *   FR-15 → Vézelay, FR-16 → Clamecy, FR-17 → La Charité, FR-18 → Bourges,
 *   FR-19 → Issoudun, FR-20 → Châteauroux, FR-21 → Argenton, FR-22 → La Souterraine,
 *   FR-23 → Le Dorat, FR-24 → Bellac, FR-25 → Oradour, FR-26 → Limoges,
 *   FR-27 → Châlus, FR-28 → Thiviers, FR-29 → Périgueux, FR-30 → Sainte-Foy,
 *   FR-31 → La Réole, FR-32 → Bazas, FR-33 → Captieux, FR-34 → Mont-de-Marsan,
 *   FR-35 → Saint-Sever, FR-36 → Orthez, FR-37 → Sauveterre, FR-38 → Saint-Palais,
 *   FR-39 → Ostabat, FR-40 → SJPP
 *
 * Sources : etapes/etapes-france.md · plan-voyage-france.md
 */
class StageSeederFrance extends Seeder
{
    public function run(): void
    {
        $campaniensis = PilgrimageRoute::where('slug', 'via-campaniensis-france')->first();
        $vezelay = PilgrimageRoute::where('slug', 'voie-vezelay-gr654-france')->first();

        if ($campaniensis === null || $vezelay === null) {
            $this->command->error('Routes FR non trouvées. Exécutez RouteSeederFrance d\'abord.');

            return;
        }

        $wp = Waypoint::whereIn('slug', [
            'rocroi-ville', 'signy-labbaye', 'chateau-porcien', 'reims-cathedrale',
            'verzy', 'chalons-en-champagne', 'vitry-le-francois', 'giffaumont-champaubert',
            'montier-en-der', 'bar-sur-seine', 'les-riceys', 'tonnerre', 'chablis',
            'auxerre', 'arcy-sur-cure', 'vezelay', 'clamecy', 'la-charite-sur-loire',
            'bourges', 'issoudun', 'chateauroux', 'argenton-sur-creuse',
            'la-souterraine', 'le-dorat', 'bellac', 'oradour-sur-glane', 'limoges',
            'chalus', 'thiviers', 'sorges', 'perigueux', 'sainte-foy-la-grande',
            'la-reole', 'bazas', 'mont-de-marsan', 'saint-sever', 'orthez',
            'sauveterre-de-bearn', 'saint-palais', 'ostabat-asme', 'saint-jean-pied-de-port',
        ])->pluck('id', 'slug');

        if ($wp->count() < 40) {
            $this->command->error(sprintf(
                'Waypoints FR manquants (%d/41 trouvés). Exécutez WaypointSeederFrance d\'abord.',
                $wp->count(),
            ));

            return;
        }

        // ── Via Campaniensis FR-01 → FR-15 ──────────────────────────────────

        $campaniensisStages = [
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-01',
                'name' => ['fr' => 'Rocroi → Signy-l\'Abbaye', 'nl' => 'Rocroi → Signy-l\'Abbaye', 'de' => 'Rocroi → Signy-l\'Abbaye'],
                'day_number' => 1,
                'start_waypoint_id' => $wp['rocroi-ville'],
                'end_waypoint_id' => $wp['signy-labbaye'],
                'distance_km' => 33.00,
                'elevation_gain_m' => 320,
                'elevation_loss_m' => 300,
                'estimated_duration_h' => 8.0,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Sortie des Ardennes par la forêt profonde. Rocroi → Sormonne (18 km) → Signy-l\'Abbaye (15 km). ⚠️ Quasi aucun commerce entre Rocroi et Signy — autonomie 36h. Abbaye cistercienne de Signy fondée 1135 (vestiges + village charmant). Étape longue : option de couper à Sormonne (18 km) si fatigue.',
                    'nl' => 'Uitstap vanuit de Ardennen via het diepe woud. ⚠️ Bijna geen winkels — 36h autonomie. Cisterciënzerabdij van Signy gesticht 1135.',
                    'de' => 'Auszug aus den Ardennen durch tiefen Wald. ⚠️ Kaum Geschäfte — 36h Autonomie. Zisterzienserkloster Signy gegründet 1135.',
                ],
                'sort_order' => 1,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-02',
                'name' => ['fr' => 'Signy-l\'Abbaye → Château-Porcien', 'nl' => 'Signy-l\'Abbaye → Château-Porcien', 'de' => 'Signy-l\'Abbaye → Château-Porcien'],
                'day_number' => 2,
                'start_waypoint_id' => $wp['signy-labbaye'],
                'end_waypoint_id' => $wp['chateau-porcien'],
                'distance_km' => 37.00,
                'elevation_gain_m' => 280,
                'elevation_loss_m' => 310,
                'estimated_duration_h' => 8.5,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Signy → Wasigny (20 km, chambre d\'hôtes) → Château-Porcien (17 km). Village perché sur l\'Aisne. Boulangerie + petite épicerie à Château-Porcien. Option de couper à Wasigny (20 km).',
                    'nl' => 'Signy → Wasigny (20 km) → Château-Porcien (17 km). Dorpje gelegen op de Aisne. Bakker + kleine winkel.',
                    'de' => 'Signy → Wasigny (20 km) → Château-Porcien (17 km). Dorf auf der Aisne. Bäckerei + kleines Geschäft.',
                ],
                'sort_order' => 2,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-03',
                'name' => ['fr' => 'Château-Porcien → Reims', 'nl' => 'Château-Porcien → Reims', 'de' => 'Château-Porcien → Reims'],
                'day_number' => 3,
                'start_waypoint_id' => $wp['chateau-porcien'],
                'end_waypoint_id' => $wp['reims-cathedrale'],
                'distance_km' => 37.00,
                'elevation_gain_m' => 210,
                'elevation_loss_m' => 240,
                'estimated_duration_h' => 8.5,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'hostel',
                'notes' => [
                    'fr' => 'Château-Porcien → Roizy (15 km, bivouac/gîte rural) → Reims (22 km). Arrivée à Reims : Cathédrale Notre-Dame (UNESCO), Palais du Tau, Basilique Saint-Remi (UNESCO), caves de champagne. Jour de repos R1 à Reims. Tampon credencial à la sacristie de la cathédrale.',
                    'nl' => 'Aankomst Reims: Kathedraal Notre-Dame (UNESCO), Palais du Tau, Sint-Remigius (UNESCO), champagnekelder. Rustdag R1 in Reims. Pelgrimsstempel aan de sacristie.',
                    'de' => 'Ankunft Reims: Notre-Dame (UNESCO), Palais du Tau, Basilika Saint-Remi (UNESCO), Champagnerkeller. Ruhetag R1 in Reims. Pilgerstempel in der Sakristei.',
                ],
                'sort_order' => 3,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-04',
                'name' => ['fr' => 'Reims → Verzy (Montagne de Reims)', 'nl' => 'Reims → Verzy (Montagne de Reims)', 'de' => 'Reims → Verzy (Montagne de Reims)'],
                'day_number' => 4,
                'start_waypoint_id' => $wp['reims-cathedrale'],
                'end_waypoint_id' => $wp['verzy'],
                'distance_km' => 20.00,
                'elevation_gain_m' => 280,
                'elevation_loss_m' => 120,
                'estimated_duration_h' => 5.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Traversée de la Montagne de Reims par Verzenay (phare-musée de la vigne). Vignobles de champagne grand cru. Nuit stratégique à Verzy pour la boucle des Faux au matin J8 (J5 du voyage). Coupe de champagne chez un vigneron de Verzy.',
                    'nl' => 'Doorkruising van de Montagne de Reims via Verzenay. Grand cru champagnewijnstokken. Strategische nacht in Verzy voor de Faux-lus.',
                    'de' => 'Durchquerung der Montagne de Reims über Verzenay. Grand Cru Champagner-Weinberge. Strategische Übernachtung in Verzy für die Faux-Runde am Morgen.',
                ],
                'sort_order' => 4,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-05',
                'name' => ['fr' => 'Verzy → Châlons-en-Champagne', 'nl' => 'Verzy → Châlons-en-Champagne', 'de' => 'Verzy → Châlons-en-Champagne'],
                'day_number' => 5,
                'start_waypoint_id' => $wp['verzy'],
                'end_waypoint_id' => $wp['chalons-en-champagne'],
                'distance_km' => 27.00,
                'elevation_gain_m' => 80,
                'elevation_loss_m' => 260,
                'estimated_duration_h' => 6.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Boucle des Faux de Verzy au lever du jour (~4 km, 90 min) avant de descendre vers Châlons. Verzy → Condé-sur-Marne → Châlons. Cathédrale Saint-Étienne + Collégiale Notre-Dame-en-Vaux (UNESCO chemins de Saint-Jacques). Marché mercredi/samedi matin.',
                    'nl' => 'Faux de Verzy-lus bij zonsopgang (~4 km, 90 min) voor de afdaling naar Châlons. Collégiale Notre-Dame-en-Vaux (UNESCO).',
                    'de' => 'Faux de Verzy Runde im Morgengrauen (~4 km, 90 Min.) vor dem Abstieg nach Châlons. Collégiale Notre-Dame-en-Vaux (UNESCO).',
                ],
                'sort_order' => 5,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-06',
                'name' => ['fr' => 'Châlons-en-Champagne → Vitry-le-François', 'nl' => 'Châlons-en-Champagne → Vitry-le-François', 'de' => 'Châlons-en-Champagne → Vitry-le-François'],
                'day_number' => 6,
                'start_waypoint_id' => $wp['chalons-en-champagne'],
                'end_waypoint_id' => $wp['vitry-le-francois'],
                'distance_km' => 34.00,
                'elevation_gain_m' => 80,
                'elevation_loss_m' => 85,
                'estimated_duration_h' => 8.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'camping',
                'notes' => [
                    'fr' => 'Châlons → La Chaussée-sur-Marne (17 km) → Vitry-le-François (17 km). Vallée de la Marne, plat et roulant. Collégiale Notre-Dame de Vitry, ville reconstruite (bombardée 1944). Super U + marché jeudi matin à Vitry.',
                    'nl' => 'Vallei van de Marne, vlak en voorspoedig. Vitry-le-François: herbouwde stad (gebombardeerd 1944).',
                    'de' => 'Marnetal, flach und gut begehbar. Vitry-le-François: wiederaufgebaute Stadt (bombardiert 1944).',
                ],
                'sort_order' => 6,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-07',
                'name' => ['fr' => 'Vitry-le-François → Giffaumont (Lac du Der)', 'nl' => 'Vitry-le-François → Giffaumont (Lac du Der)', 'de' => 'Vitry-le-François → Giffaumont (Lac du Der)'],
                'day_number' => 7,
                'start_waypoint_id' => $wp['vitry-le-francois'],
                'end_waypoint_id' => $wp['giffaumont-champaubert'],
                'distance_km' => 22.00,
                'elevation_gain_m' => 90,
                'elevation_loss_m' => 80,
                'estimated_duration_h' => 5.5,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'camping',
                'notes' => [
                    'fr' => 'Arrivée au Lac du Der-Chantecoq (4 800 ha, plus grand lac artificiel de France). Étape de migration des grues cendrées (oct-nov et fév-mars). Églises à pans de bois autour du lac. Campings nombreux (réserver en été).',
                    'nl' => 'Aankomst aan het Lac du Der-Chantecoq (4 800 ha, grootste kunstmatige meer van Frankrijk). Trekkranen-trekplaats (okt-nov en feb-mrt). Vakwerkkerken rondom het meer.',
                    'de' => 'Ankunft am Lac du Der-Chantecoq (4 800 ha, größter Stausee Frankreichs). Kranich-Rastplatz (Okt-Nov und Feb-März). Fachwerkkirchen rund um den See.',
                ],
                'sort_order' => 7,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-08',
                'name' => ['fr' => 'Giffaumont → Montier-en-Der', 'nl' => 'Giffaumont → Montier-en-Der', 'de' => 'Giffaumont → Montier-en-Der'],
                'day_number' => 8,
                'start_waypoint_id' => $wp['giffaumont-champaubert'],
                'end_waypoint_id' => $wp['montier-en-der'],
                'distance_km' => 15.00,
                'elevation_gain_m' => 80,
                'elevation_loss_m' => 75,
                'estimated_duration_h' => 3.5,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Abbatiale Saint-Pierre-Saint-Paul (Xe siècle) à Montier-en-Der. Haras national. Intermarché + boulangeries. Étape courte — après-midi libre pour la visite du lac.',
                    'nl' => 'Abdijkerk Sint-Pieter-Sint-Paulus (10e eeuw) in Montier-en-Der. Nationaal stoeterij. Korte etappe.',
                    'de' => 'Stiftskirche Saint-Pierre-Saint-Paul (10. Jh.) in Montier-en-Der. Nationales Gestüt. Kurze Etappe.',
                ],
                'sort_order' => 8,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-09',
                'name' => ['fr' => 'Montier-en-Der → Bar-sur-Seine', 'nl' => 'Montier-en-Der → Bar-sur-Seine', 'de' => 'Montier-en-Der → Bar-sur-Seine'],
                'day_number' => 9,
                'start_waypoint_id' => $wp['montier-en-der'],
                'end_waypoint_id' => $wp['bar-sur-seine'],
                'distance_km' => 45.00,
                'elevation_gain_m' => 380,
                'elevation_loss_m' => 360,
                'estimated_duration_h' => 10.0,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Champagne humide → Côte des Bar. Montier → Soulaines-Dhuys (22 km) → Dienville/Lac d\'Amance (20 km) → Bar-sur-Seine (23 km). Option de couper en 2 jours. ⚠️ Villages espacés, commerces rares — toujours 24h d\'avance. Bar-sur-Seine : Intermarché, marché vendredi matin, caves de champagne vignerons.',
                    'nl' => 'Vochtige Champagne → Côte des Bar. Option om in 2 dagen te splitsen. Bar-sur-Seine: Intermarché, vrijdagmarkt, champagnekelder.',
                    'de' => 'Feuchte Champagne → Côte des Bar. Option auf 2 Tage aufzuteilen. Bar-sur-Seine: Intermarché, Freitagsmarkt, Champagnerkeller.',
                ],
                'sort_order' => 9,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-10',
                'name' => ['fr' => 'Bar-sur-Seine → Les Riceys', 'nl' => 'Bar-sur-Seine → Les Riceys', 'de' => 'Bar-sur-Seine → Les Riceys'],
                'day_number' => 10,
                'start_waypoint_id' => $wp['bar-sur-seine'],
                'end_waypoint_id' => $wp['les-riceys'],
                'distance_km' => 18.00,
                'elevation_gain_m' => 200,
                'elevation_loss_m' => 190,
                'estimated_duration_h' => 4.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Les Riceys : seul village de France avec 3 AOC (champagne, coteaux champenois, rosé des Riceys — le rosé préféré de Louis XIV). Caves familiales, épicerie, boulangerie.',
                    'nl' => 'Les Riceys: enig dorp in Frankrijk met 3 AOC (champagne, coteaux champenois, rosé des Riceys). Familiekelder.',
                    'de' => 'Les Riceys: einziges Dorf Frankreichs mit 3 AOC (Champagne, Coteaux Champenois, Rosé des Riceys). Familienkeller.',
                ],
                'sort_order' => 10,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-11',
                'name' => ['fr' => 'Les Riceys → Tonnerre', 'nl' => 'Les Riceys → Tonnerre', 'de' => 'Les Riceys → Tonnerre'],
                'day_number' => 11,
                'start_waypoint_id' => $wp['les-riceys'],
                'end_waypoint_id' => $wp['tonnerre'],
                'distance_km' => 40.00,
                'elevation_gain_m' => 320,
                'elevation_loss_m' => 330,
                'estimated_duration_h' => 9.0,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Les Riceys → Étourvy/Channes (16 km) → Tonnerre (24 km). Fosse Dionne à Tonnerre : source vauclusienne bleu turquoise, lavoir circulaire (voir !). Hôtel-Dieu de Tonnerre (1293). Super U + marché samedi matin. Option de couper à Étourvy.',
                    'nl' => 'Fosse Dionne in Tonnerre: turquoise vauclusische bron, rond wasplaats. Hôtel-Dieu (1293). Super U + zaterdagmarkt.',
                    'de' => 'Fosse Dionne in Tonnerre: türkisfarbene Vaucluse-Quelle, runder Waschplatz. Hôtel-Dieu (1293). Super U + Samstagmarkt.',
                ],
                'sort_order' => 11,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-12',
                'name' => ['fr' => 'Tonnerre → Chablis', 'nl' => 'Tonnerre → Chablis', 'de' => 'Tonnerre → Chablis'],
                'day_number' => 12,
                'start_waypoint_id' => $wp['tonnerre'],
                'end_waypoint_id' => $wp['chablis'],
                'distance_km' => 18.00,
                'elevation_gain_m' => 180,
                'elevation_loss_m' => 190,
                'estimated_duration_h' => 4.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Capitale du vin blanc de Bourgogne. Dégustation cave coopérative La Chablisienne ou vigneron (avec modération, étape demain). ⚠️ Ravitailler plutôt à Tonnerre — épicerie fine chère à Chablis.',
                    'nl' => 'Hoofdstad van de Bourgondische witte wijn. Degustatie bij La Chablisienne of wijnboer (met mate). ⚠️ Beter ravitailleren in Tonnerre.',
                    'de' => 'Hauptstadt des burgundischen Weißweins. Degustation bei La Chablisienne oder Winzer (mit Maß). ⚠️ Besser in Tonnerre verproviantieren.',
                ],
                'sort_order' => 12,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-13',
                'name' => ['fr' => 'Chablis → Auxerre', 'nl' => 'Chablis → Auxerre', 'de' => 'Chablis → Auxerre'],
                'day_number' => 13,
                'start_waypoint_id' => $wp['chablis'],
                'end_waypoint_id' => $wp['auxerre'],
                'distance_km' => 20.00,
                'elevation_gain_m' => 160,
                'elevation_loss_m' => 190,
                'estimated_duration_h' => 5.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'hostel',
                'notes' => [
                    'fr' => 'Cathédrale Saint-Étienne d\'Auxerre (crypte carolingienne ⭐), Abbaye Saint-Germain, Tour de l\'Horloge, quais de l\'Yonne. Repos flottant possible ici. Marchés mar/ven/dim + halles. AJ (~25 €) + accueil paroissial.',
                    'nl' => 'Kathedraal Saint-Étienne (carolingische crypte ⭐), Abdij Saint-Germain, Quai de l\'Yonne. Zwevende rustdag mogelijk. Markten dia/vr/zo.',
                    'de' => 'Kathedrale Saint-Étienne (karolingische Krypta ⭐), Abtei Saint-Germain, Quai de l\'Yonne. Möglicher Ruhetag. Märkte Di/Fr/So.',
                ],
                'sort_order' => 13,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-14',
                'name' => ['fr' => 'Auxerre → Arcy-sur-Cure', 'nl' => 'Auxerre → Arcy-sur-Cure', 'de' => 'Auxerre → Arcy-sur-Cure'],
                'day_number' => 14,
                'start_waypoint_id' => $wp['auxerre'],
                'end_waypoint_id' => $wp['arcy-sur-cure'],
                'distance_km' => 34.00,
                'elevation_gain_m' => 280,
                'elevation_loss_m' => 270,
                'estimated_duration_h' => 8.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Auxerre → Vermenton (18 km) → Arcy-sur-Cure (16 km, vallée de la Cure). Grottes d\'Arcy-sur-Cure (~1 km du tracé) : peintures paléolithiques 28 000 ans, 2e plus anciennes de France après Chauvet. Visite guidée ~10 €. Gîtes d\'étape en vallée.',
                    'nl' => 'Grottes d\'Arcy-sur-Cure (~1 km van tracé): paleolithische schilderijen 28 000 jaar, 2e oudste van Frankrijk. Rondleiding ~10 €.',
                    'de' => 'Höhlen von Arcy-sur-Cure (~1 km vom Weg): paläolithische Malereien 28 000 Jahre, 2. älteste Frankreichs. Führung ~10 €.',
                ],
                'sort_order' => 14,
            ],
            [
                'route_id' => $campaniensis->id,
                'code' => 'FR-15',
                'name' => ['fr' => 'Arcy-sur-Cure → Vézelay', 'nl' => 'Arcy-sur-Cure → Vézelay', 'de' => 'Arcy-sur-Cure → Vézelay'],
                'day_number' => 15,
                'start_waypoint_id' => $wp['arcy-sur-cure'],
                'end_waypoint_id' => $wp['vezelay'],
                'distance_km' => 18.00,
                'elevation_gain_m' => 280,
                'elevation_loss_m' => 200,
                'estimated_duration_h' => 4.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Montée vers la colline éternelle. Basilique Sainte-Marie-Madeleine (UNESCO) : tympan roman du Christ en gloire, crypte avec reliques de Marie-Madeleine. Credencial n°2 à retirer. Repos R2 à Vézelay. Fraternités monastiques de Jérusalem : messe/vêpres. Hôtellerie de Vézelay : réserver 2-3 jours avant.',
                    'nl' => 'Beklimming naar de eeuwige heuvel. Basiliek Sainte-Marie-Madeleine (UNESCO). Credencial nr. 2 afhalen. Rustdag R2. Fraterniteiten van Jeruzalem: mis/vespers.',
                    'de' => 'Aufstieg zum ewigen Hügel. Basilika Sainte-Marie-Madeleine (UNESCO). Credencial Nr. 2 abholen. Ruhetag R2. Jerusalemer Brüder: Messe/Vesper.',
                ],
                'sort_order' => 15,
            ],
        ];

        // ── Voie de Vézelay GR654 FR-16 → FR-40 ─────────────────────────────

        $vezelayStages = [
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-16',
                'name' => ['fr' => 'Vézelay → Clamecy', 'nl' => 'Vézelay → Clamecy', 'de' => 'Vézelay → Clamecy'],
                'day_number' => 1,
                'start_waypoint_id' => $wp['vezelay'],
                'end_waypoint_id' => $wp['clamecy'],
                'distance_km' => 23.00,
                'elevation_gain_m' => 240,
                'elevation_loss_m' => 290,
                'estimated_duration_h' => 5.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Première étape du GR654. Clamecy : cité médiévale du flottage du bois, collégiale Saint-Martin. Intermarché + marché samedi matin. Début du réseau des refuges Vézelay Compostelle.',
                    'nl' => 'Eerste etappe van de GR654. Clamecy: middeleeuwse stad van houtdrijvers, collégiale Saint-Martin. Intermarché + zaterdagmarkt.',
                    'de' => 'Erste Etappe der GR654. Clamecy: mittelalterliche Holztreiberstadt, Stiftskirche Saint-Martin.',
                ],
                'sort_order' => 1,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-17',
                'name' => ['fr' => 'Clamecy → La Charité-sur-Loire', 'nl' => 'Clamecy → La Charité-sur-Loire', 'de' => 'Clamecy → La Charité-sur-Loire'],
                'day_number' => 2,
                'start_waypoint_id' => $wp['clamecy'],
                'end_waypoint_id' => $wp['la-charite-sur-loire'],
                'distance_km' => 35.00,
                'elevation_gain_m' => 260,
                'elevation_loss_m' => 290,
                'estimated_duration_h' => 8.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Clamecy → Varzy (17 km) → Châteauneuf-Val-de-Bargis (18 km, gîte rural) → La Charité-sur-Loire (17 km). Prieuré clunisien Notre-Dame (UNESCO) — "Fille aînée de Cluny", ville du livre. Traversée de la Loire au pont de pierre. Accueil pèlerin donativo.',
                    'nl' => 'Cluniacenzerpriorij Notre-Dame (UNESCO) — La Charité-sur-Loire. Oversteek Loire over stenen brug. Donativo pelgrimsopvang.',
                    'de' => 'Cluniazenserpriorat Notre-Dame (UNESCO). Überquerung der Loire auf der Steinbrücke. Donativo-Pilgeraufnahme.',
                ],
                'sort_order' => 2,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-18',
                'name' => ['fr' => 'La Charité-sur-Loire → Bourges', 'nl' => 'La Charité-sur-Loire → Bourges', 'de' => 'La Charité-sur-Loire → Bourges'],
                'day_number' => 3,
                'start_waypoint_id' => $wp['la-charite-sur-loire'],
                'end_waypoint_id' => $wp['bourges'],
                'distance_km' => 53.00,
                'elevation_gain_m' => 310,
                'elevation_loss_m' => 290,
                'estimated_duration_h' => 11.5,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'hostel',
                'notes' => [
                    'fr' => 'La Charité → Sancergues (17 km) → Sainte-Solange (19 km) → Bourges (17 km). Option de couper en 2-3 jours. Cathédrale Saint-Étienne (UNESCO, la plus large nef gothique de France) + Palais Jacques-Cœur. Repos R3 à Bourges. AJ Cujas + accueil diocésain.',
                    'nl' => 'Kathedraal Saint-Étienne (UNESCO, breedste gotisch schip). Palais Jacques-Cœur. Rustdag R3. Option om in 2-3 dagen te splitsen.',
                    'de' => 'Kathedrale Saint-Étienne (UNESCO, breitestes gotisches Schiff). Palais Jacques-Cœur. Ruhetag R3. Option auf 2-3 Tage aufzuteilen.',
                ],
                'sort_order' => 3,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-19',
                'name' => ['fr' => 'Bourges → Issoudun', 'nl' => 'Bourges → Issoudun', 'de' => 'Bourges → Issoudun'],
                'day_number' => 4,
                'start_waypoint_id' => $wp['bourges'],
                'end_waypoint_id' => $wp['issoudun'],
                'distance_km' => 37.00,
                'elevation_gain_m' => 180,
                'elevation_loss_m' => 190,
                'estimated_duration_h' => 8.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Bourges → Charost (22 km) → Issoudun (15 km). Berry profond. Issoudun : basilique Notre-Dame du Sacré-Cœur, tour Blanche (Richard Cœur de Lion). Intermarché + marché samedi. Pâté berrichon aux pommes de terre au dîner.',
                    'nl' => 'Diep Berry. Issoudun: basiliek Notre-Dame du Sacré-Cœur, Witte Toren (Richard Leeuwenhart). Berrichons pataataardappeltaart bij het avondeten.',
                    'de' => 'Tiefes Berry. Issoudun: Basilika Notre-Dame du Sacré-Cœur, Weißer Turm (Richard Löwenherz). Berrichon-Kartoffelkuchen zum Abendessen.',
                ],
                'sort_order' => 4,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-20',
                'name' => ['fr' => 'Issoudun → Châteauroux', 'nl' => 'Issoudun → Châteauroux', 'de' => 'Issoudun → Châteauroux'],
                'day_number' => 5,
                'start_waypoint_id' => $wp['issoudun'],
                'end_waypoint_id' => $wp['chateauroux'],
                'distance_km' => 29.00,
                'elevation_gain_m' => 150,
                'elevation_loss_m' => 160,
                'estimated_duration_h' => 7.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Issoudun → Neuvy-Pailloux (15 km) → Châteauroux (14 km). Couvent des Cordeliers, vieille ville de Châteauroux. Marché samedi. Grande ville pour matériel/pharmacie.',
                    'nl' => 'Châteauroux: Cordelierenklooster, oude binnenstad. Zaterdagmarkt. Grote stad voor materieel/apotheek.',
                    'de' => 'Châteauroux: Cordelierkloster, Altstadt. Samstagmarkt. Große Stadt für Ausrüstung/Apotheke.',
                ],
                'sort_order' => 5,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-21',
                'name' => ['fr' => 'Châteauroux → Argenton-sur-Creuse', 'nl' => 'Châteauroux → Argenton-sur-Creuse', 'de' => 'Châteauroux → Argenton-sur-Creuse'],
                'day_number' => 6,
                'start_waypoint_id' => $wp['chateauroux'],
                'end_waypoint_id' => $wp['argenton-sur-creuse'],
                'distance_km' => 31.00,
                'elevation_gain_m' => 260,
                'elevation_loss_m' => 250,
                'estimated_duration_h' => 7.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Châteauroux → Velles (15 km) → Argenton-sur-Creuse (16 km). "Venise du Berry" : vieux ponts, gué, paysage de la Creuse. Super U + marché samedi. Gargilesse-Dampierre (Plus Beau Village de France, maison de George Sand) en légère variante.',
                    'nl' => '"Venetië van Berry": oude bruggen, doorwaadbare plaatsen, Creuse-landschap. Gargilesse-Dampierre (Mooiste Dorp van Frankrijk, huis van George Sand) in lichte variant.',
                    'de' => '"Venedig des Berry": alte Brücken, Furten, Creuse-Landschaft. Gargilesse-Dampierre (Schönstes Dorf Frankreichs, Haus von George Sand) in leichter Variante.',
                ],
                'sort_order' => 6,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-22',
                'name' => ['fr' => 'Argenton → La Souterraine', 'nl' => 'Argenton → La Souterraine', 'de' => 'Argenton → La Souterraine'],
                'day_number' => 7,
                'start_waypoint_id' => $wp['argenton-sur-creuse'],
                'end_waypoint_id' => $wp['la-souterraine'],
                'distance_km' => 42.00,
                'elevation_gain_m' => 490,
                'elevation_loss_m' => 470,
                'estimated_duration_h' => 10.0,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Argenton → Gargilesse → Crozant (22 km) → La Souterraine (20 km). Ruines de Crozant sur le GR654 (forteresse médiévale sur éperon, paysages de Monet + Guillaumin). La Souterraine : porte Saint-Jean, crypte. Intermarché + marché jeudi/samedi. Option de couper à Crozant.',
                    'nl' => 'Ruïnes van Crozant op de GR654 (middeleeuwse burcht, landschappen van Monet + Guillaumin). La Souterraine: Sint-Janpoort, crypte. Option om bij Crozant te splitsen.',
                    'de' => 'Ruinen von Crozant auf der GR654 (mittelalterliche Burg, Landschaften von Monet + Guillaumin). La Souterraine: Johannistor, Krypta. Option bei Crozant aufzuteilen.',
                ],
                'sort_order' => 7,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-23',
                'name' => ['fr' => 'La Souterraine → Le Dorat', 'nl' => 'La Souterraine → Le Dorat', 'de' => 'La Souterraine → Le Dorat'],
                'day_number' => 8,
                'start_waypoint_id' => $wp['la-souterraine'],
                'end_waypoint_id' => $wp['le-dorat'],
                'distance_km' => 25.00,
                'elevation_gain_m' => 290,
                'elevation_loss_m' => 280,
                'estimated_duration_h' => 6.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Collégiale Saint-Pierre du Dorat (granit roman limousin ⭐) — chef-d\'œuvre roman limousin. Bœuf limousin grillé au dîner. Épicerie + boulangerie au Dorat.',
                    'nl' => 'Collégiale Saint-Pierre van Le Dorat (limousijns romaans graniet ⭐). Limousin-rund gegrild bij het avondeten.',
                    'de' => 'Stiftskirche Saint-Pierre von Le Dorat (limousiner romanischer Granit ⭐). Gegrilltes Limousin-Rind zum Abendessen.',
                ],
                'sort_order' => 8,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-24',
                'name' => ['fr' => 'Le Dorat → Bellac', 'nl' => 'Le Dorat → Bellac', 'de' => 'Le Dorat → Bellac'],
                'day_number' => 9,
                'start_waypoint_id' => $wp['le-dorat'],
                'end_waypoint_id' => $wp['bellac'],
                'distance_km' => 13.00,
                'elevation_gain_m' => 160,
                'elevation_loss_m' => 170,
                'estimated_duration_h' => 3.0,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Étape courte (13 km) — visite Le Dorat le matin. Mortemart (Plus Beau Village de France, halles, château des Ducs) à intégrer si passage. Carrefour Contact Bellac + marché samedi.',
                    'nl' => 'Korte etappe (13 km) — bezoek Le Dorat \'s ochtends. Mortemart (Mooiste Dorp van Frankrijk) eventueel inbegrepen. Carrefour Contact Bellac.',
                    'de' => 'Kurze Etappe (13 km) — Besuch Le Dorat am Morgen. Mortemart (Schönstes Dorf Frankreichs) ggf. integriert. Carrefour Contact Bellac.',
                ],
                'sort_order' => 9,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-25',
                'name' => ['fr' => 'Bellac → Oradour-sur-Glane', 'nl' => 'Bellac → Oradour-sur-Glane', 'de' => 'Bellac → Oradour-sur-Glane'],
                'day_number' => 10,
                'start_waypoint_id' => $wp['bellac'],
                'end_waypoint_id' => $wp['oradour-sur-glane'],
                'distance_km' => 25.00,
                'elevation_gain_m' => 270,
                'elevation_loss_m' => 260,
                'estimated_duration_h' => 6.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Variante ouest GR654 — Oradour-sur-Glane intégré au tracé (aucun détour). 642 habitants massacrés le 10 juin 1944. Village ruines gratuit + Centre de la Mémoire (~8 €). Prévoir 2-3 h, silence demandé. Étape volontairement courte : l\'émotion est réelle. Chambre d\'hôtes à Oradour ou Saint-Junien (6 km).',
                    'nl' => 'Westelijke GR654-variant — Oradour-sur-Glane geïntegreerd (geen omweg). 642 inwoners vermoord 10 juni 1944. Gratis ruïnesdorp + Geheugencentrum (~8 €). 2-3 uur voorzien, stilte vereist.',
                    'de' => 'Westvariante GR654 — Oradour-sur-Glane integriert (kein Umweg). 642 Einwohner massakriert 10. Juni 1944. Kostenlose Ruinen + Gedenkzentrum (~8 €). 2-3 Stunden einplanen, Stille.',
                ],
                'sort_order' => 10,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-26',
                'name' => ['fr' => 'Oradour-sur-Glane → Limoges', 'nl' => 'Oradour-sur-Glane → Limoges', 'de' => 'Oradour-sur-Glane → Limoges'],
                'day_number' => 11,
                'start_waypoint_id' => $wp['oradour-sur-glane'],
                'end_waypoint_id' => $wp['limoges'],
                'distance_km' => 24.00,
                'elevation_gain_m' => 200,
                'elevation_loss_m' => 230,
                'estimated_duration_h' => 6.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'hostel',
                'notes' => [
                    'fr' => 'Arrivée à Limoges. Repos R4 mérité après la séquence émotionnelle d\'Oradour. Gare des Bénédictins (art déco), cathédrale Saint-Étienne, musée national de la porcelaine Adrien-Dubouché, quartier de la Boucherie. Halles centrales tous les jours ⭐. Décathlon/Intersport — 2e paire de chaussures à envisager (~1 100 km cumulés).',
                    'nl' => 'Aankomst Limoges. Rustdag R4 na emotionele Oradour-sequentie. Gare des Bénédictins (art deco), porseleinmuseum, halles dagelijks open. Decathlon/Intersport — 2e paar schoenen overwegen.',
                    'de' => 'Ankunft Limoges. Ruhetag R4 nach emotionaler Oradour-Sequenz. Gare des Bénédictins (Art Déco), Porzellanmuseum. Halles täglich offen. Decathlon/Intersport — 2. Paar Schuhe erwägen.',
                ],
                'sort_order' => 11,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-27',
                'name' => ['fr' => 'Limoges → Châlus', 'nl' => 'Limoges → Châlus', 'de' => 'Limoges → Châlus'],
                'day_number' => 12,
                'start_waypoint_id' => $wp['limoges'],
                'end_waypoint_id' => $wp['chalus'],
                'distance_km' => 40.00,
                'elevation_gain_m' => 480,
                'elevation_loss_m' => 430,
                'estimated_duration_h' => 9.5,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Limoges → Aixe-sur-Vienne → Flavignac (25 km, refuge associatif) → Châlus (15 km). Château de Châlus-Chabrol : Richard Cœur de Lion y meurt d\'un carreau d\'arbalète (1199). Vue sur les monts de Châlus. Option de couper à Flavignac.',
                    'nl' => 'Château de Châlus-Chabrol: Richard Leeuwenhart sterft aan een armbooststoot (1199). Uitzicht op de Chalus-bergen. Option bij Flavignac splitsen.',
                    'de' => 'Château de Châlus-Chabrol: Richard Löwenherz stirbt an einem Armbrustpfeil (1199). Aussicht auf die Châlus-Berge. Option bei Flavignac aufzuteilen.',
                ],
                'sort_order' => 12,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-28',
                'name' => ['fr' => 'Châlus → Thiviers', 'nl' => 'Châlus → Thiviers', 'de' => 'Châlus → Thiviers'],
                'day_number' => 13,
                'start_waypoint_id' => $wp['chalus'],
                'end_waypoint_id' => $wp['thiviers'],
                'distance_km' => 33.00,
                'elevation_gain_m' => 340,
                'elevation_loss_m' => 350,
                'estimated_duration_h' => 8.0,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Châlus → La Coquille (17 km, refuge associatif) → Thiviers (17 km). Capitale du foie gras du Périgord vert. Musée + marché samedi matin (foie gras en saison). Intermarché. Option de couper à La Coquille.',
                    'nl' => 'Hoofdstad van de Périgord vert-ganzenleverkoeien. Museum + zaterdagmarkt (ganzenleverkoeien in seizoen). Option bij La Coquille splitsen.',
                    'de' => 'Hauptstadt der Périgord-vert-Gänsestopfleber. Museum + Samstagmarkt (Gänsestopfleber in Saison). Option bei La Coquille aufzuteilen.',
                ],
                'sort_order' => 13,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-29',
                'name' => ['fr' => 'Thiviers → Périgueux', 'nl' => 'Thiviers → Périgueux', 'de' => 'Thiviers → Périgueux'],
                'day_number' => 14,
                'start_waypoint_id' => $wp['thiviers'],
                'end_waypoint_id' => $wp['perigueux'],
                'distance_km' => 36.00,
                'elevation_gain_m' => 310,
                'elevation_loss_m' => 330,
                'estimated_duration_h' => 8.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Thiviers → Sorges (16 km, écomusée de la Truffe, capitale de la truffe, refuge ouvert jusqu\'au 31 oct) → Périgueux (20 km). Cathédrale Saint-Front (UNESCO, coupoles byzantines). L\'Eschif de Creyssac : loge de guet à colombages de 1347, meilleur point photo des quais. Repos R5 à Périgueux. Marché place du Coderc (mer/sam).',
                    'nl' => 'Sorges (16 km, truffelmuseum, refuge open tot 31 okt) → Périgueux (20 km). Kathedraal Saint-Front (UNESCO, Byzantijnse koepels). Eschif de Creyssac: wachthuis 1347. Rustdag R5. Markt woensdag/zaterdag.',
                    'de' => 'Sorges (16 km, Trüffelmuseum, Refuge bis 31. Okt. geöffnet) → Périgueux (20 km). Kathedrale Saint-Front (UNESCO, byzantinische Kuppeln). Eschif de Creyssac: Wachhaus 1347. Ruhetag R5. Markt Mi/Sa.',
                ],
                'sort_order' => 14,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-30',
                'name' => ['fr' => 'Périgueux → Sainte-Foy-la-Grande', 'nl' => 'Périgueux → Sainte-Foy-la-Grande', 'de' => 'Périgueux → Sainte-Foy-la-Grande'],
                'day_number' => 15,
                'start_waypoint_id' => $wp['perigueux'],
                'end_waypoint_id' => $wp['sainte-foy-la-grande'],
                'distance_km' => 60.00,
                'elevation_gain_m' => 520,
                'elevation_loss_m' => 510,
                'estimated_duration_h' => 13.0,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Périgueux → Saint-Astier (18 km) → Mussidan (20 km) → Villefranche-de-Lonchat (22 km) → Sainte-Foy-la-Grande (18 km). À faire en 3 jours. Bastide XIIIe sur la Dordogne. Marché samedi matin — un des plus beaux de France ⭐⭐. Saint-Ferme (refuge, ouvert jusqu\'au 31 oct).',
                    'nl' => 'Étape in 3 dagen te verdelen. Sainte-Foy-la-Grande: bastide 13e eeuw aan de Dordogne. Zaterdagmarkt — een van de mooiste van Frankrijk ⭐⭐.',
                    'de' => 'Etappe auf 3 Tage aufzuteilen. Sainte-Foy-la-Grande: Bastide 13. Jh. an der Dordogne. Samstagmarkt — einer der schönsten Frankreichs ⭐⭐.',
                ],
                'sort_order' => 15,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-31',
                'name' => ['fr' => 'Sainte-Foy-la-Grande → La Réole', 'nl' => 'Sainte-Foy-la-Grande → La Réole', 'de' => 'Sainte-Foy-la-Grande → La Réole'],
                'day_number' => 16,
                'start_waypoint_id' => $wp['sainte-foy-la-grande'],
                'end_waypoint_id' => $wp['la-reole'],
                'distance_km' => 39.00,
                'elevation_gain_m' => 320,
                'elevation_loss_m' => 340,
                'estimated_duration_h' => 9.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Sainte-Foy → Monségur (22 km, bastide anglaise perchée) → La Réole (17 km). La Réole : ville d\'Art et d\'Histoire sur la Garonne, prieuré bénédictin, plus vieil hôtel de ville de France (XIIe siècle). Marché samedi.',
                    'nl' => 'Monségur (bastide op een heuvel) → La Réole. Stad van Kunst en Geschiedenis aan de Garonne, benedictijnerpriori, oudste stadhuis van Frankrijk (12e eeuw).',
                    'de' => 'Monségur (Bastide auf dem Hügel) → La Réole. Stadt der Kunst und Geschichte an der Garonne, Benediktinerpriorat, ältestes Rathaus Frankreichs (12. Jh.).',
                ],
                'sort_order' => 16,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-32',
                'name' => ['fr' => 'La Réole → Bazas', 'nl' => 'La Réole → Bazas', 'de' => 'La Réole → Bazas'],
                'day_number' => 17,
                'start_waypoint_id' => $wp['la-reole'],
                'end_waypoint_id' => $wp['bazas'],
                'distance_km' => 20.00,
                'elevation_gain_m' => 200,
                'elevation_loss_m' => 190,
                'estimated_duration_h' => 5.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Bazas : cathédrale Saint-Jean-Baptiste (UNESCO chemins de Saint-Jacques), place à arcades médiévale. Bœuf de Bazas AOC (entrecôte grillée aux sarments). ⚠️ Ravitailler ici pour 48 h — Landes ensuite. Super U + marché samedi.',
                    'nl' => 'Bazas: kathedraal Sint-Jan de Doper (UNESCO). Boeuf de Bazas AOC (gegrilde entrecote op wijnranken). ⚠️ Hier ravitailleren voor 48u — Landes daarna. Super U + zaterdagmarkt.',
                    'de' => 'Bazas: Kathedrale Saint-Jean-Baptiste (UNESCO). Boeuf de Bazas AOC (gegrilltes Entrecôte auf Weinreben). ⚠️ Hier für 48h verproviantieren — Landes danach. Super U + Samstagmarkt.',
                ],
                'sort_order' => 17,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-33',
                'name' => ['fr' => 'Bazas → Captieux', 'nl' => 'Bazas → Captieux', 'de' => 'Bazas → Captieux'],
                'day_number' => 18,
                'start_waypoint_id' => $wp['bazas'],
                'end_waypoint_id' => $wp['mont-de-marsan'],
                'distance_km' => 49.00,
                'elevation_gain_m' => 120,
                'elevation_loss_m' => 125,
                'estimated_duration_h' => 11.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'camping',
                'notes' => [
                    'fr' => 'Bazas → Captieux (22 km) → Roquefort (27 km — forêt landaise, plat, hypnotique). ⚠️ Forêt des Landes : eau rare, villages espacés. Partir chaque matin avec 2,5-3 L. ⚠️ Pas de bivouac sauvage dans les pins (forêt privée + risque incendie). Gîtes communaux + campings municipaux uniquement.',
                    'nl' => 'Landese woud, vlak, hypnotisch. ⚠️ Water zeldzaam, dorpen ver uit elkaar. Elke ochtend met 2,5-3 L vertrekken. ⚠️ Geen wild bivakkeren in het dennenbos (privé + brandgevaar).',
                    'de' => 'Landès-Wald, flach, hypnotisch. ⚠️ Wasser selten, Dörfer weit auseinander. Jeden Morgen mit 2,5-3 L starten. ⚠️ Kein Wildzelten in den Kiefern (Privatwald + Brandgefahr).',
                ],
                'sort_order' => 18,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-34',
                'name' => ['fr' => 'Roquefort → Mont-de-Marsan', 'nl' => 'Roquefort → Mont-de-Marsan', 'de' => 'Roquefort → Mont-de-Marsan'],
                'day_number' => 19,
                'start_waypoint_id' => $wp['mont-de-marsan'],
                'end_waypoint_id' => $wp['mont-de-marsan'],
                'distance_km' => 23.00,
                'elevation_gain_m' => 80,
                'elevation_loss_m' => 90,
                'estimated_duration_h' => 5.5,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Sortie des Landes. Mont-de-Marsan : confluence Douze-Midou, musée Despiau-Wlérick (sculpture figurative), arènes. Repos R6. Marchés mar/sam. Garbure landaise + pastis landais au dîner.',
                    'nl' => 'Uitgang Landes. Mont-de-Marsan: samenvloeiing Douze-Midou, museum Despiau-Wlérick. Rustdag R6. Markten di/za.',
                    'de' => 'Ausgang Landes. Mont-de-Marsan: Zusammenfluss Douze-Midou, Museum Despiau-Wlérick. Ruhetag R6. Märkte Di/Sa.',
                ],
                'sort_order' => 19,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-35',
                'name' => ['fr' => 'Mont-de-Marsan → Saint-Sever', 'nl' => 'Mont-de-Marsan → Saint-Sever', 'de' => 'Mont-de-Marsan → Saint-Sever'],
                'day_number' => 20,
                'start_waypoint_id' => $wp['mont-de-marsan'],
                'end_waypoint_id' => $wp['saint-sever'],
                'distance_km' => 17.00,
                'elevation_gain_m' => 180,
                'elevation_loss_m' => 170,
                'estimated_duration_h' => 4.5,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Abbatiale de Saint-Sever (UNESCO chemins de Saint-Jacques) — chapiteaux romans polychromes ⭐. Début de la Chalosse vallonnée. Carrefour Contact + marché samedi. Poulet fermier des Landes label rouge au dîner.',
                    'nl' => 'Abdijkerk Saint-Sever (UNESCO) — polychrome romaanse kapiteelbeeldhouwwerken ⭐. Begin van de heuvelachtige Chalosse. Landse boerenkip label rouge bij het avondeten.',
                    'de' => 'Abteikirche Saint-Sever (UNESCO) — polychrome romanische Kapitelle ⭐. Beginn der hügeligen Chalosse. Landaise Bauernhähnchen Label Rouge zum Abendessen.',
                ],
                'sort_order' => 20,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-36',
                'name' => ['fr' => 'Saint-Sever → Orthez', 'nl' => 'Saint-Sever → Orthez', 'de' => 'Saint-Sever → Orthez'],
                'day_number' => 21,
                'start_waypoint_id' => $wp['saint-sever'],
                'end_waypoint_id' => $wp['orthez'],
                'distance_km' => 41.00,
                'elevation_gain_m' => 380,
                'elevation_loss_m' => 360,
                'estimated_duration_h' => 9.5,
                'difficulty' => 'hard',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Saint-Sever → Hagetmau (15 km, Intermarché) → Orthez (26 km — longue, option couper à Sault-de-Navailles). Pont Vieux fortifié XIIIe, ancienne capitale du Béarn (Gaston Fébus). Le paysage devient pyrénéen. Garbure béarnaise + Ossau-Iraty au dîner.',
                    'nl' => 'Saint-Sever → Hagetmau (15 km) → Orthez (26 km — lang, optie bij Sault-de-Navailles splitsen). Pont Vieux 13e, vroegere hoofdstad van Béarn. Garbure béarnaise + Ossau-Iraty.',
                    'de' => 'Saint-Sever → Hagetmau (15 km) → Orthez (26 km — lang, Option bei Sault-de-Navailles aufzuteilen). Pont Vieux 13. Jh., frühere Hauptstadt des Béarn. Garbure béarnaise + Ossau-Iraty.',
                ],
                'sort_order' => 21,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-37',
                'name' => ['fr' => 'Orthez → Sauveterre-de-Béarn', 'nl' => 'Orthez → Sauveterre-de-Béarn', 'de' => 'Orthez → Sauveterre-de-Béarn'],
                'day_number' => 22,
                'start_waypoint_id' => $wp['orthez'],
                'end_waypoint_id' => $wp['sauveterre-de-bearn'],
                'distance_km' => 21.00,
                'elevation_gain_m' => 280,
                'elevation_loss_m' => 270,
                'estimated_duration_h' => 5.5,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Sauveterre-de-Béarn ⭐ : village médiéval au-dessus du gave d\'Oloron, pont de la Légende — l\'un des plus beaux points de vue du tronçon. Truite du gave au dîner. Épicerie + boulangerie.',
                    'nl' => 'Sauveterre-de-Béarn ⭐: middeleeuws dorp boven de gave d\'Oloron, Pont de la Légende — een van de mooiste uitzichten van het traject.',
                    'de' => 'Sauveterre-de-Béarn ⭐: mittelalterliches Dorf über der Gave d\'Oloron, Pont de la Légende — einer der schönsten Aussichtspunkte des Abschnitts.',
                ],
                'sort_order' => 22,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-38',
                'name' => ['fr' => 'Sauveterre-de-Béarn → Saint-Palais', 'nl' => 'Sauveterre-de-Béarn → Saint-Palais', 'de' => 'Sauveterre-de-Béarn → Saint-Palais'],
                'day_number' => 23,
                'start_waypoint_id' => $wp['sauveterre-de-bearn'],
                'end_waypoint_id' => $wp['saint-palais'],
                'distance_km' => 13.00,
                'elevation_gain_m' => 180,
                'elevation_loss_m' => 170,
                'estimated_duration_h' => 3.5,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Capitale de la Basse-Navarre. Musée de Basse-Navarre et des chemins de Saint-Jacques. Carrefour Contact + marché vendredi (marché au gras en saison). Axoa de veau au piment d\'Espelette au dîner. Le trafic jacquaire augmente à l\'approche de la convergence.',
                    'nl' => 'Hoofdstad van Laag-Navarra. Museum van Laag-Navarra en de Jacobswegen. Axoa van kalf met Espelette-peper bij het avondeten. Jacobsverkeer neemt toe.',
                    'de' => 'Hauptstadt der Basse-Navarre. Museum der Basse-Navarre und der Jakobswege. Axoa vom Kalb mit Espelette-Pfeffer zum Abendessen. Pilgerverkehr nimmt zu.',
                ],
                'sort_order' => 23,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-39',
                'name' => ['fr' => 'Saint-Palais → Ostabat-Asme (stèle de Gibraltar)', 'nl' => 'Saint-Palais → Ostabat-Asme (stèle van Gibraltar)', 'de' => 'Saint-Palais → Ostabat-Asme (Stele von Gibraltar)'],
                'day_number' => 24,
                'start_waypoint_id' => $wp['saint-palais'],
                'end_waypoint_id' => $wp['ostabat-asme'],
                'distance_km' => 12.00,
                'elevation_gain_m' => 200,
                'elevation_loss_m' => 190,
                'estimated_duration_h' => 3.0,
                'difficulty' => 'easy',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Stèle de Gibraltar ⭐ : lieu symbolique où convergent les trois voies françaises de Compostelle (Tours, Vézelay, Le Puy). À partir d\'ici, tous les pèlerins marchent ensemble. Ostabat-Asme : village-étape médiéval historique, ambiance pèlerine forte, chants basques au dîner. Gîtes historiques (Maison Ospitalia…).',
                    'nl' => 'Stèle van Gibraltar ⭐: symbolische plek waar de drie Franse pelgrimswegen samenkomen. Ostabat-Asme: historisch middeleeuws pelgrimsdorp, Baskische liederen.',
                    'de' => 'Stele von Gibraltar ⭐: symbolischer Ort wo die drei französischen Jakobswege zusammentreffen. Ostabat-Asme: historisches mittelalterliches Pilgerdorf, Baskische Lieder.',
                ],
                'sort_order' => 24,
            ],
            [
                'route_id' => $vezelay->id,
                'code' => 'FR-40',
                'name' => ['fr' => 'Ostabat → Saint-Jean-Pied-de-Port', 'nl' => 'Ostabat → Saint-Jean-Pied-de-Port', 'de' => 'Ostabat → Saint-Jean-Pied-de-Port'],
                'day_number' => 25,
                'start_waypoint_id' => $wp['ostabat-asme'],
                'end_waypoint_id' => $wp['saint-jean-pied-de-port'],
                'distance_km' => 20.00,
                'elevation_gain_m' => 280,
                'elevation_loss_m' => 240,
                'estimated_duration_h' => 5.0,
                'difficulty' => 'moderate',
                'accommodation_type_default' => 'gite',
                'notes' => [
                    'fr' => 'Porte Saint-Jacques (UNESCO). Accueil pèlerin 39 rue de la Citadelle : credencial n°3, conseils, statistiques. Gâteau basque + Irouléguy + piperade + brebis-confiture. 2 jours de repos R7-R8 : récupération fin traversée française (~1 350 km depuis Liège) + bascule vers l\'approche basque du Norte. ⚠️ Tu ne montes PAS à Roncevaux.',
                    'nl' => 'Porte Saint-Jacques (UNESCO). Pelgrimsopvang 39 rue de la Citadelle: credencial nr. 3. Baskische cake + Irouléguy. 2 rustdagen R7-R8. ⚠️ Je gaat NIET naar Roncevaux.',
                    'de' => 'Porte Saint-Jacques (UNESCO). Pilgerempfang 39 Rue de la Citadelle: Credencial Nr. 3. Baskischer Kuchen + Irouléguy. 2 Ruhetage R7-R8. ⚠️ Du gehst NICHT nach Roncesvalles.',
                ],
                'sort_order' => 25,
            ],
        ];

        $allStages = array_merge($campaniensisStages, $vezelayStages);
        $count = 0;

        foreach ($allStages as $stage) {
            Stage::updateOrCreate(
                ['code' => $stage['code']],
                $stage
            );
            $count++;
        }

        $this->command->info(sprintf('StageSeederFrance : %d étapes FR créées/mises à jour.', $count));
    }
}
