<?php

declare(strict_types=1);

namespace App\Modules\Pilgrimage\Database\Seeders;

use App\Modules\Pilgrimage\Models\Waypoint;
use Illuminate\Database\Seeder;

class WaypointSeeder extends Seeder
{
    public function run(): void
    {
        $waypoints = [
            // ── Villes-étapes (city) ────────────────────────────────────────────
            [
                'slug' => 'liege-cathedrale',
                'name' => ['fr' => 'Liège — Cathédrale Saint-Paul', 'nl' => 'Luik — Sint-Pauluskathedraal', 'de' => 'Lüttich — St.-Pauls-Kathedrale'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.6458,
                'longitude' => 5.5718,
                'is_active' => true,
            ],
            [
                'slug' => 'amay',
                'name' => ['fr' => 'Amay', 'nl' => 'Amay', 'de' => 'Amay'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.5500,
                'longitude' => 5.3225,
                'is_active' => true,
            ],
            [
                'slug' => 'huy',
                'name' => ['fr' => 'Huy', 'nl' => 'Hoei', 'de' => 'Huy'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.5206,
                'longitude' => 5.2381,
                'is_active' => true,
            ],
            [
                'slug' => 'andenne',
                'name' => ['fr' => 'Andenne', 'nl' => 'Andenne', 'de' => 'Andenne'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.4803,
                'longitude' => 5.0942,
                'is_active' => true,
            ],
            [
                'slug' => 'namur',
                'name' => ['fr' => 'Namur', 'nl' => 'Namen', 'de' => 'Namur'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.4674,
                'longitude' => 4.8714,
                'is_active' => true,
            ],
            [
                'slug' => 'yvoir',
                'name' => ['fr' => 'Yvoir', 'nl' => 'Yvoir', 'de' => 'Yvoir'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.3250,
                'longitude' => 4.8800,
                'is_active' => true,
            ],
            [
                'slug' => 'dinant',
                'name' => ['fr' => 'Dinant', 'nl' => 'Dinant', 'de' => 'Dinant'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.2617,
                'longitude' => 4.9139,
                'is_active' => true,
            ],
            [
                'slug' => 'hastiere',
                'name' => ['fr' => 'Hastière', 'nl' => 'Hastière', 'de' => 'Hastière'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.2050,
                'longitude' => 4.8300,
                'is_active' => true,
            ],
            [
                'slug' => 'givet',
                'name' => ['fr' => 'Givet (FR)', 'nl' => 'Givet (FR)', 'de' => 'Givet (FR)'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.1400,
                'longitude' => 4.8250,
                'is_active' => true,
            ],
            [
                'slug' => 'doische',
                'name' => ['fr' => 'Doische', 'nl' => 'Doische', 'de' => 'Doische'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.1550,
                'longitude' => 4.7200,
                'is_active' => true,
            ],
            [
                'slug' => 'olloy-sur-viroin',
                'name' => ['fr' => 'Olloy-sur-Viroin', 'nl' => 'Olloy-sur-Viroin', 'de' => 'Olloy-sur-Viroin'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.1000,
                'longitude' => 4.6200,
                'is_active' => true,
            ],
            [
                'slug' => 'couvin',
                'name' => ['fr' => 'Couvin', 'nl' => 'Couvin', 'de' => 'Couvin'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 50.0500,
                'longitude' => 4.4900,
                'is_active' => true,
            ],
            [
                'slug' => 'rocroi',
                'name' => ['fr' => 'Rocroi (FR)', 'nl' => 'Rocroi (FR)', 'de' => 'Rocroi (FR)'],
                'type' => 'city',
                'poi_category' => null,
                'latitude' => 49.9267,
                'longitude' => 4.5253,
                'is_active' => true,
            ],

            // ── POI remarquables ────────────────────────────────────────────────
            [
                'slug' => 'grotte-scladina-sclayn',
                'name' => ['fr' => 'Grotte Scladina', 'nl' => 'Grot Scladina', 'de' => 'Höhle Scladina'],
                'type' => 'poi',
                'poi_category' => 'archaeology',
                'latitude' => 50.4820,
                'longitude' => 5.0140,
                'detour_type' => 'medium',
                'detour_distance_km' => 1.50,
                'detour_duration_min' => 45,
                'visit_duration_min' => 90,
                'entry_cost_eur' => 8.00,
                'booking_required' => true,
                'booking_contact' => 'grotte@scladina.be',
                'opening_notes' => [
                    'fr' => '1er dimanche du mois à 14h uniquement (sauf janvier). Réservation OBLIGATOIRE.',
                    'nl' => '1e zondag van de maand om 14u (behalve januari). Reservering VERPLICHT.',
                    'de' => '1. Sonntag des Monats um 14 Uhr (außer Januar). Reservierung PFLICHT.',
                ],
                'description' => [
                    'fr' => 'Site archéologique majeur. L\'Enfant de Scladina — Néandertalien de +100 000 ans découvert en 1971.',
                    'nl' => 'Belangrijk archeologisch site. Het Kind van Scladina — Neanderthaler van +100.000 jaar.',
                    'de' => 'Bedeutende archäologische Stätte. Das Kind von Scladina — Neandertaler von +100.000 Jahren.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'passage-eau-waulsort',
                'name' => ['fr' => 'Passage d\'eau de Waulsort', 'nl' => 'Veerpont van Waulsort', 'de' => 'Fähre von Waulsort'],
                'type' => 'poi',
                'poi_category' => 'nature',
                'latitude' => 50.2100,
                'longitude' => 4.8600,
                'detour_type' => 'medium',
                'detour_distance_km' => 2.00,
                'detour_duration_min' => 30,
                'visit_duration_min' => 20,
                'entry_cost_eur' => 0.00,
                'booking_required' => false,
                'description' => [
                    'fr' => 'Dernier passeur d\'eau manuel de Wallonie en activité depuis 1871. Bac à câble, gratuit, traversée 10 min.',
                    'nl' => 'Laatste handmatige veerpont van Wallonië, in gebruik since 1871. Kabelboot, gratis, 10 minuten oversteek.',
                    'de' => 'Letzte manuelle Fähre Walloniens seit 1871. Gratis, 10 Minuten Überfahrt.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'roche-a-lomme-dourbes',
                'name' => ['fr' => 'Roche à Lomme', 'nl' => 'Roche à Lomme', 'de' => 'Roche à Lomme'],
                'type' => 'poi',
                'poi_category' => 'archaeology',
                'latitude' => 50.0880,
                'longitude' => 4.6550,
                'detour_type' => 'medium',
                'detour_distance_km' => 3.00,
                'detour_duration_min' => 60,
                'visit_duration_min' => 60,
                'entry_cost_eur' => 0.00,
                'booking_required' => false,
                'description' => [
                    'fr' => 'Promontoire calcaire classé Patrimoine exceptionnel de Wallonie (2009). Grande croix au sommet, panorama exceptionnel sur la vallée du Viroin.',
                    'nl' => 'Kalkstenen klif, uitzonderlijk erfgoed Wallonië (2009). Groot kruis op de top, uitzonderlijk panorama over de Viroin-vallei.',
                    'de' => 'Kalksteinklippe, außergewöhnliches Erbe Walloniens (2009). Großes Kreuz auf dem Gipfel, außergewöhnliches Panorama über das Viroin-Tal.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'grotte-neptune-petigny',
                'name' => ['fr' => 'Grotte de Neptune', 'nl' => 'Grot van Neptunus', 'de' => 'Neptun-Höhle'],
                'type' => 'poi',
                'poi_category' => 'nature',
                'latitude' => 50.0550,
                'longitude' => 4.5250,
                'detour_type' => 'medium',
                'detour_distance_km' => 2.50,
                'detour_duration_min' => 30,
                'visit_duration_min' => 45,
                'entry_cost_eur' => 12.00,
                'booking_required' => false,
                'booking_contact' => '060 31 19 54',
                'description' => [
                    'fr' => 'Grotte karstique avec rivière souterraine navigable en barque. Visite guidée 45 min mêlant marche et barque.',
                    'nl' => 'Karstgrot met ondergrondse rivier, bevaarbaar per boot. Rondleiding 45 min.',
                    'de' => 'Karsthöhle mit unterirdischem Fluss, per Boot befahrbar. Geführte Tour 45 Min.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'forteresse-poilvache',
                'name' => ['fr' => 'Forteresse de Poilvache', 'nl' => 'Vesting van Poilvache', 'de' => 'Festung Poilvache'],
                'type' => 'poi',
                'poi_category' => 'fortress',
                'latitude' => 50.3350,
                'longitude' => 4.8950,
                'detour_type' => 'medium',
                'detour_distance_km' => 3.00,
                'detour_duration_min' => 60,
                'visit_duration_min' => 60,
                'entry_cost_eur' => 4.00,
                'booking_required' => false,
                'description' => [
                    'fr' => 'Ruines XIIIe sur éperon rocheux 150m au-dessus de la Meuse. Panorama exceptionnel sur les méandres mosans.',
                    'nl' => 'Ruïnes 13e eeuw op rotsrug 150m boven de Maas. Uitzonderlijk panorama op de Maas-meanders.',
                    'de' => 'Ruinen des 13. Jahrhunderts auf Felssporn 150m über der Maas. Außergewöhnliches Panorama.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'citadelle-namur',
                'name' => ['fr' => 'Citadelle de Namur', 'nl' => 'Citadel van Namen', 'de' => 'Zitadelle von Namur'],
                'type' => 'poi',
                'poi_category' => 'fortress',
                'latitude' => 50.4581,
                'longitude' => 4.8619,
                'detour_type' => 'short',
                'detour_distance_km' => 0.50,
                'detour_duration_min' => 30,
                'visit_duration_min' => 120,
                'entry_cost_eur' => 0.00,
                'booking_required' => false,
                'description' => [
                    'fr' => 'L\'une des plus grandes citadelles d\'Europe. Montée à pied (30 min) ou petit train. Vue sur le confluent Sambre-Meuse.',
                    'nl' => 'Een van de grootste citadellen van Europa. Te voet (30 min) of toeristisch treintje. Zicht op confluent.',
                    'de' => 'Eine der größten Zitadellen Europas. Zu Fuß (30 Min.) oder Touristenzug. Blick auf Mündung.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'rocroi-etoilee',
                'name' => ['fr' => 'Rocroi étoilée (Vauban)', 'nl' => 'Rocroi (Vauban)', 'de' => 'Rocroi (Vauban)'],
                'type' => 'poi',
                'poi_category' => 'fortress',
                'latitude' => 49.9267,
                'longitude' => 4.5253,
                'detour_type' => 'on_path',
                'detour_distance_km' => 0.00,
                'booking_required' => false,
                'description' => [
                    'fr' => 'Ville étoilée à cinq branches, chef-d\'œuvre Vauban XVIIe, intégralement classée Monument Historique.',
                    'nl' => 'Vijfhoekige vestingstad, meesterwerk van Vauban (17e eeuw), volledig beschermd.',
                    'de' => 'Fünfeckige Festungsstadt, Meisterwerk von Vauban (17. Jh.), vollständig unter Denkmalschutz.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'li-rondia-huy',
                'name' => ['fr' => 'Li Rondia — Collégiale Notre-Dame de Huy', 'nl' => 'Li Rondia — Onze-Lieve-Vrouwe van Hoei', 'de' => 'Li Rondia — Stiftskirche Huy'],
                'type' => 'poi',
                'poi_category' => 'religious',
                'latitude' => 50.5206,
                'longitude' => 5.2381,
                'detour_type' => 'on_path',
                'detour_distance_km' => 0.00,
                'visit_duration_min' => 30,
                'booking_required' => false,
                'description' => [
                    'fr' => 'Rosace de 9m de diamètre, XIVe siècle gothique flamboyant. L\'une des 4 merveilles de Huy.',
                    'nl' => 'Roosvenster van 9m diameter, 14e eeuws. Een van de 4 wonderen van Hoei.',
                    'de' => 'Rundfenster 9m Durchmesser, 14. Jh. gotisch. Eines der 4 Wunder von Huy.',
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'fort-charlemont-givet',
                'name' => ['fr' => 'Fort Charlemont', 'nl' => 'Fort Charlemont', 'de' => 'Fort Charlemont'],
                'type' => 'poi',
                'poi_category' => 'fortress',
                'latitude' => 50.1400,
                'longitude' => 4.8250,
                'detour_type' => 'short',
                'detour_distance_km' => 1.00,
                'detour_duration_min' => 30,
                'visit_duration_min' => 60,
                'entry_cost_eur' => 4.00,
                'booking_required' => false,
                'description' => [
                    'fr' => 'Chef-d\'œuvre Vauban XVIIe siècle. Vue sur la vallée de la Meuse depuis les hauteurs de Givet.',
                    'nl' => 'Meesterwerk van Vauban (17e eeuw). Zicht op de Maas-vallei vanuit de hoogte van Givet.',
                    'de' => 'Meisterwerk von Vauban (17. Jh.). Blick über das Maastal von den Höhen Givets.',
                ],
                'is_active' => true,
            ],
        ];

        foreach ($waypoints as $waypoint) {
            Waypoint::updateOrCreate(
                ['slug' => $waypoint['slug']],
                $waypoint
            );
        }

        $this->command->info(sprintf('WaypointSeeder : %d waypoints créés/mis à jour.', count($waypoints)));
    }
}
